name: fetch-api
on: 
   schedule:
     - cron: '0 4 * * *'
jobs:
  fetch-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: installing jq
        run: |
         sudo apt install -y jq
      - name: Fetching data
        run: |
         wget -O temp.json phip.si
      - name: transforming data
        run: |
         rm js/butchers.json
         cat temp.json | jq '.elements' > js/butchers.json
         rm temp.json
      - name: Commit and push changes
        run: |
          
          git config --global user.name ${{secrets.GITUSER}} 
          git config --global user.email ${{secrets.GITEMAIL}} 
          git add js/butchers.json -v
          git commit -m 'Updated list with butchers'
          git push
